version: '3.7'

services:
  dm_db:
    image: postgres:10.1-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    ports:
      - 5435:5432
  dm_web:
    build: .
    command: python /usr/src/blog_django/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/blog_django
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - dm_db

volumes:
  database:
